name: Build

on:
  push:
    branches: [DEV-29518]
  schedule:
    - cron: "0 2 * * *" # Everyday at 2:00AM
  workflow_dispatch:
    inputs:
      reason:
        description: "Trigger Comment (Optional)"
        required: false
        default: "Manual Workflow Run"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Using a different secret name for the URL to harmonize secrets
      # between integrations

      # TODO Are these env variables used or directly the secrets env?

      TEST_SERVER_URL:       ${{ secrets.TEST_SERVER_URL }}
      ACROLINX_API_USERNAME: ${{ secrets.ACROLINX_API_USERNAME }}
      ACROLINX_API_TOKEN:    ${{ secrets.ACROLINX_API_TOKEN }}
      SSO_GENERIC_TOKEN:     ${{ secrets.SSO_GENERIC_TOKEN }}
      SSO_USERNAME:          ${{ secrets.SSO_USERNAME }}
      GITHUB_TOKEN:          ${{ secrets.GITHUB_TOKEN }}
      ACROLINX_DEV_SIGNATURE: ${{ secrets.ACROLINX_DEV_SIGNATURE}}

    # TODO add timeout
    # TODO Provide Node & npm bin/ folder to PATH
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.JS
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Build And Run Tests
        run: |
          npm ci
          npm run ci
          npm run docs
      
      - name: Setup and Audit Source Code    
        run: |
          npm ci
          npm audit --production --audit-level=moderate
      
      - name: Check For Suitable Licenses
        run: |
         export v=`node -p "require('./package.json').version"`
         export n=`node -p "require('./package.json').name"`
         npx license-checker --production --onlyAllow 'BSD;CC-PDDC;CC-BY-3.0;CC-BY-1.0;CC-BY-2.0;CC-BY-4.0;CC0-1.0;Apache;Artistic;MIT;MPL;ISC;Unlicense' --excludePackages "$n@$v$LICENSE_EXCLUDED_PACKAGES" --excludePrivatePackages
      
      - name: Archive Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: |
            dist/**/*
            tmp/reports/coverage/**/cobertura-coverage.xml
