name: Build and Deploy

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 2 * * *" # Everyday at 2:00AM
  workflow_dispatch:
    inputs:
      reason:
        description: "Trigger Comment (Optional)"
        required: false
        default: "Manual Workflow Run"
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TEST_SERVER_URL:       ${{ secrets.TEST_SERVER_URL }}
      ACROLINX_API_USERNAME: ${{ secrets.ACROLINX_API_USERNAME }}
      ACROLINX_API_TOKEN:    ${{ secrets.ACROLINX_API_TOKEN }}
      SSO_GENERIC_TOKEN:     ${{ secrets.SSO_GENERIC_TOKEN }}
      SSO_USERNAME:          ${{ secrets.SSO_USERNAME }}
      GITHUB_TOKEN:          ${{ secrets.GITHUB_TOKEN }}
      ACROLINX_DEV_SIGNATURE: ${{ secrets.ACROLINX_DEV_SIGNATURE}}
      ACROLINX_ONE_SERVER_URL: ${{ secrets.ACROLINX_ONE_SERVER_URL}}
      KEYCLOAK_TENANT_ID: ${{ secrets.KEYCLOAK_TENANT_ID}}
      KEYCLOAK_CLIENT_ID: ${{ secrets.KEYCLOAK_CLIENT_ID}}
      KEYCLOAK_REFRESH_TOKEN: ${{ secrets.KEYCLOAK_REFRESH_TOKEN}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.JS
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build And Run Tests
        run: |
          npm ci
          npm run ci
          npm run docs
      
      - name: Setup and Audit Source Code    
        run: |
          npm ci
          npm audit --production --audit-level=moderate
      
      - name: Check For Suitable Licenses
        run: |
         export v=`node -p "require('./package.json').version"`
         export n=`node -p "require('./package.json').name"`
         npx license-checker --production --onlyAllow 'BSD;CC-PDDC;CC-BY-3.0;CC-BY-1.0;CC-BY-2.0;CC-BY-4.0;CC0-1.0;Apache;Artistic;MIT;MPL;ISC;Unlicense' --excludePackages "$n@$v$LICENSE_EXCLUDED_PACKAGES" --excludePrivatePackages
      
      - name: Archive Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: |
            dist/**/*
            tmp/reports/coverage/**/cobertura-coverage.xml

      - name: Publish To NPM
        id: publish
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_ACCESS_TOKEN }}
      
      - name: Push Tag
        uses: anothrNick/github-tag-action@1.64.0
        if: steps.publish.outputs.type
        env:
          CUSTOM_TAG: v${{ steps.publish.outputs.version }}
      
      - name: Publish GitHub Pages 🚀
        if: steps.publish.outputs.type
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: docs/pluginDoc
