name: CI Acrolinx sdk-js

on:
  # Triggers the workflow on push or pull request events
  # but only for the master branch
  push:
    branches:
      - build-migration
      # tags:
      #   - 'v*'

# set to master branch
# pull_request:
#   # master
#   branches:
#     - build-migration
# schedule:
#   # TODO verify schedule
#   - cron: "0 2 * * *"
# # Allows you to run this workflow manually from the Actions tab
# # workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # , macos-latest, windows-latest
        os: [ubuntu-latest, macos-latest, windows-latest]
        # 12.x, , 15.x
        node: [12]
    env:
      ACROLINX_API_TOKEN: ${{secrets.ACROLINX_API_TOKEN}}
      ACROLINX_API_USERNAME: api-js-test-user
      ACROLINX_TEST_SERVER_URL: https://unstable.acrolinx.com

    # TODO add timeout
    # TODO Provide Node & npm bin/ folder to PATH
    steps:
      - uses: actions/checkout@v2

      - name: Test sdk-js-matrix
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - run: |
          node -v
          npm -v
          npm ci
          echo ACROLINX_TEST_SERVER_URL $ACROLINX_TEST_SERVER_URL
          # without test coverage which is currently failing
          # npm run build && npm run lint && npm run test && npm run testMarkdown
          npm run ci
