name: Build and Deploy

on:
  push:
    branches:
      - build-migration
      # tags:
      #   - 'v*'

# set to master branch
# pull_request:
#   # master
#   branches:
#     - build-migration
# schedule:
#   # TODO verify schedule
#   - cron: "0 2 * * *"
# # Allows you to run this workflow manually from the Actions tab
# # workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Using a different secret name for the URL to harmonize secrets
      # between integrations

      # TODO Are these env variables used or directly the secrets env?

      TEST_SERVER_URL:       ${{ secrets.TEST_SERVER_URL }}
      ACROLINX_API_USERNAME: ${{ secrets.ACROLINX_API_USERNAME }}
      ACROLINX_API_TOKEN:    ${{ secrets.ACROLINX_API_TOKEN }}
      SSO_GENERIC_TOKEN:     ${{ secrets.SSO_GENERIC_TOKEN }}
      SSO_USERNAME:          ${{ secrets.SSO_USERNAME }}

    # TODO add timeout
    # TODO Provide Node & npm bin/ folder to PATH
    steps:
      - name: checkout the code
        uses: actions/checkout@v2

      - name: setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Build And Run Tests
        run: |
          npm ci
          npm run ci
