name: CI Acrolinx sdk-js

on:
  # Triggers the workflow on push or pull request events
  # but only for the master branch
  push:
    branches:
      - build-migration
      # tags:
      #   - 'v*'

# set to master branch
# pull_request:
#   # master
#   branches:
#     - build-migration
# schedule:
#   # TODO verify schedule
#   - cron: "0 2 * * *"
# # Allows you to run this workflow manually from the Actions tab
# # workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # , macos-latest, windows-latest
        os: [ubuntu-latest]
        # 12.x, , 15.x
        node: [12]
    env:
      # ACROLINX_API_USERNAME: api-js-test-user
      # TEST_SERVER_URL: https://unstable.acrolinx.com
      # ACROLINX_API_USERNAME: sdk-js-github-ci-tests

      # Using a different secret name for the URL to harmonize secrets
      # between integrations

      # TODO Are these env variables used or directly the secrets env?
      TEST_SERVER_URL:       ${{ secrets.TEST_SERVER_URL }}
      ACROLINX_API_USERNAME: ${{ secrets.ACROLINX_API_USERNAME }}
      ACROLINX_API_TOKEN:    ${{ secrets.ACROLINX_API_TOKEN }}
      SSO_GENERIC_TOKEN:     ${{ secrets.SSO_GENERIC_TOKEN }}
      SSO_USERNAME:          sdk-js-github-ci-tests

    # TODO add timeout
    # TODO Provide Node & npm bin/ folder to PATH
    steps:
      - name: checkout the code
        uses: actions/checkout@v2

      - name: setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: run the CI tests
        run: |
          node -v
          npm -v
          npm ci
          echo TEST_SERVER_URL $TEST_SERVER_URL
          # without test coverage which is currently failing
          # npm run build && npm run lint && npm run test && npm run testMarkdown
          npm run ci
