name: Matrix Test

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    env:
      TEST_SERVER_URL:       ${{ secrets.TEST_SERVER_URL }}
      ACROLINX_API_USERNAME: ${{ secrets.ACROLINX_API_USERNAME }}
      ACROLINX_API_TOKEN:    ${{ secrets.ACROLINX_API_TOKEN }}
      SSO_GENERIC_TOKEN:     ${{ secrets.SSO_GENERIC_TOKEN }}
      SSO_USERNAME:          ${{ secrets.SSO_USERNAME }}
      ACROLINX_DEV_SIGNATURE: ${{ secrets.ACROLINX_DEV_SIGNATURE}}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [14.x]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
  
      - name: Compile and Test
        run: |
          npm ci
          npm run ci
